#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2022 VipFreinds
#
# This file is a part of < https://github.com/sakil0007/TeraBhainagraaj/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/sakil0007/TeraBhainagraaj/blob/main/LICENSE/>.


Basic "
            ┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┳━╋╋┛┃
            ┃┃┃┗┫┏┫┏┫╋┃┃╋┃
            ┗━┻━┻━┻┛┗━┻┻━┛

      Visit @VipFreinds for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyUltroid ; fi
